# Generated by Django 5.2.1 on 2025-05-23 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_film_auteur_enquete_evaluationenquete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionjeu',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 23, 12, 27, 53, 489587, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionjeu',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé'), ('abandonne', 'Abandonné')], default='en_cours', max_length=10),
        ),
    ]
