# Generated by Django 5.2.3 on 2025-06-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionJeu',
        ),
    ]
