# Generated by Django 5.2.1 on 2025-05-23 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='films', to='movies.auteur'),
        ),
        migrations.CreateModel(
            name='Enquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('scenario_json', models.TextField()),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=10)),
                ('evaluation_moyenne', models.FloatField(default=0.0)),
                ('nombre_evaluations', models.IntegerField(default=0)),
                ('nombre_parties', models.IntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquetes_crees', to=settings.AUTH_USER_MODEL)),
                ('film_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquetes', to='movies.film')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationEnquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(choices=[(1, '1 étoiles'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')])),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='movies.enquete')),
                ('evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('evaluateur', 'enquete')},
            },
        ),
        migrations.CreateModel(
            name='SessionJeu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etape_actuelle', models.IntegerField(default=1)),
                ('enquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='movies.enquete')),
                ('joueur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_jeu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('joueur', 'enquete')},
            },
        ),
    ]
